---
- name: get zk tar bar
  get_url:
    url: https://archive.apache.org/dist/zookeeper/zookeeper-3.4.9/zookeeper-3.4.9.tar.gz
    dest: "{{ software }}/"

- name: unzip zk tar bar
  shell:
    "tar -xzf {{ software }}/zookeeper-3.4.9.tar.gz -C /usr/local/"

- name: rename zk config
  copy:
    src: zoo.cfg  
    dest: "{{ software }}/zookeeper-3.4.9/conf/zoo.cfg"

- name: run zk server
  shell: 
    "{{ software }}/zookeeper-3.4.9/bin/zkServer.sh  start"