---
- name: "Install zabbix_server "
  hosts: zabbix_server
  remote_user: root

  vars_files: 
   - var/main.yml
  
  roles:
   - zabbix_server

- name: "Install zabbix_agent "
  hosts: zabbix_agent
  remote_user: root

  vars_files: 
   - var/main.yml
  
  roles:
   - zabbix_agent