---
- name: "Install zabbix repo"
  yum:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    state: present

- name: "Install zabbix agent"
  yum:
    name: "{{ zabbix_agent_packages }}"
    state: latest

- name: "move templates to zabbix agentd"
  template:
    src: zabbix_agentd.conf
    dest: "{{ zbwork }}/zabbix_agentd.conf"
  notify:
    - restart zabbix-agentd